---
title: "1) Intro"
---


## 📖 Lecture

Welcome to STAT 33B. Our first meeting is on Monday Jan-27 where we begin with the usual review of the course policies, logistics, overall expectations, topics in a nutshell, etc.

 

## 🔬 Lab

The first lab is on Wednesday Jan-29 where you'll get started with R and RStudio: first, we want to make sure everybody has installed both programs; and then we will provide an introductory review of RStudio's workspace, as well as a brief intro to Quarto notebooks. 

Also, we'll review the basics of Quarto Markdown (qmd) files, how to "compile" them and produce an HTML document. Also, you'll have the opportunity to make sure you know how to submit a qmd & HTML files to bCourses.

BTW: there's nothing to submit this week.

 

## 🔔 Activities

If you haven't yet, please spend some time outside class to review the following documentation:

- <a href="../syllabus.html" target="_blank">syllabus</a>
- <a href="../email.html" target="_blank">communication via email</a>
- <a href="../faqs.html" target="_blank">some frequently asked questions</a>



## 📢 Install R & RStudio

For those of you that don't have either R or RStudio, download and install these programs (both are free, and they are available for Mac, Windows, and Linux computers)

- <a href="https://cran.r-project.org/" target="_blank">Install R</a>

- <a href="https://www.rstudio.com/products/rstudio/download/#download" target="_blank">Install RStudio</a> (Desktop free version)

